blueprint:
  name: Blinds Sun Mode
  description: Controls blinds tilt based on trigger entity
  domain: automation
  input:
    entity_name:
      name: Entity Name
      description: Name of the entity (e.g., Kitchen)
      selector:
        text:
    target_device_id:
      name: Target Device ID
      description: The device ID of the cover to control
      selector:
        device:
          integration: cover
          domain: cover
    target_entity_id:
      name: Target Entity ID
      description: The entity ID of the cover to control
      selector:
        entity:
          domain: cover

alias: "{{ input.entity_name }} blinds sun mode"
description: "Controls blinds tilt based on trigger entity"
trigger:
  - platform: state
    entity_id: this
condition: []
action:
  - device_id: !input target_device_id
    domain: cover
    entity_id: !input target_entity_id
    type: close
  - wait_for_trigger:
      - platform: device
        device_id: !input target_device_id
        domain: cover
        entity_id: !input target_entity_id
        type: closed
  - device_id: !input target_device_id
    domain: cover
    entity_id: !input target_entity_id
    type: set_tilt_position
    position: 100
mode: single
